### ISSUE TITLE
Project Purpose?

### ISSUE THREAD

**Issue by SDGGiesbrecht** [pqmarkup/pqmarkup-lite#2]
Is this a tool that will actually be put to use, or is its purpose more to be a side‐by‐side demonstration of various computer languages?

I ask because for the latter case, the throwing of error messages is a significant part of the demonstration. But for the former, it would probably be better never to fail no matter what the source contains. For most of the ways markup is used, users expect an error in one place not to prevent the proper handling of the rest of the document.

- *For* **example**, ~the~ `Markdown` *engine* **used** ~on~ `GitHub` *still* **allows** ~me~ `to` *post* **this** ~paragraph~ `and` *handles* **most** ~of~ `it` *correctly* **even** ~though~ `there` *is* **an** ~error~ `at` *the* **very** ~end.

The Python reference implementation currently hits hard failures in some situations, but just ignores partial syntax in others. Is that intentional?

If failure is integral to the specification, then another set of tests would be helpful to ensure that the various implementations all fail with the same message in expected situations.

If failure should instead be avoided, then examples with malformed syntax can simply be added to the existing test list.

(I have a lot of poorly defined edge cases with surprising behaviour to add to the test suite, but this question needs to be decided on first.)

**Comment by alextretyak** [comment]
> Is this a tool that will actually be put to use, or is its purpose more to be a side‐by‐side demonstration of various computer languages?

Well, *pqmarkup* is a tool that ~~will actually be put to use~~ is already actively used by myself for writing articles and comments on [Habr](https://habr.com), for web-pages and documentation of my projects (e.g. [11l programming language](http://11l-lang.org)), and even for e-mails.

*pqmarkup-lite* is a stripped-down version of *pqmarkup*, which main purpose is a side‐by‐side demonstration of various programming languages [including performance comparison]. But it also has a partially practical application—it can translate to HTML my diary records (they looks like [i.data](https://github.com/pqmarkup/pqmarkup-lite/blob/master/i.data) file).

> The Python reference implementation currently hits hard failures in some situations, but just ignores partial syntax in others.

Can you give some examples?

> I ask because for the latter case, the throwing of error messages is a significant part of the demonstration.

It will be good to throw the same error messages as a Python implementation throws, but it is not required.
The only requirements that must be satisfied by pqmarkup-lite implementations:
1. All tests in tests.txt must be passed [using -t command line flag].
2. Output HTML-file generated for [i.data](https://github.com/pqmarkup/pqmarkup-lite/blob/master/i.data) input file must be the same as generated by Python implementation (i.e. after executing commands `python pqmarkup_lite.py i.data out.html` and `your_implementation i.data out2.html`, files out.html and out2.html must be the same).

I think that throwing a few [3-5] error messages should be enough to demonstrate how errors are handled in the particular programming language.

**Comment by SDGGiesbrecht** [comment]
>> The Python reference implementation currently hits hard failures in some situations, but just ignores partial syntax in others.
>
> Can you give some examples?

This produces nothing:

```text
*‘Missing end
```

```text
Unpaired left single quotation mark at line 1, column 2
```

But this sneaks through without so much as a warning:

```text
*‘H()‘Incomplete Header’’
```

```html
<b>H(1‘Incomplete Header’</b>
```

**Comment by alextretyak** [comment]
I think that both behaviours are acceptable.
