### ISSUE TITLE
Bug in C++ implementation?

### ISSUE THREAD

**Issue by ExpHP** [pqmarkup/pqmarkup-lite#5]
https://github.com/pqmarkup/pqmarkup-lite/blob/7d9bc7df692311ce4b964f3ddb17c06b8dcd933b/cpp/utf8/utf8.cpp#L520

Noticed this while trying to adapt the C++ implementation.  I don't think this loop will ever run?  Were the C++ implementations tested or do the tests just not catch this?

**Comment by ExpHP** [comment]
Well this is embarassing.  Delta is negative in the branch.

(I feel this does say something about the clarity of the code though...)

Also found where it does the tests.

**Comment by alextretyak** [comment]
This is a direct translation of corresponding Python code:
https://github.com/pqmarkup/pqmarkup-lite/blob/7d9bc7df692311ce4b964f3ddb17c06b8dcd933b/pqmarkup_lite.py#L328-L335

How do you propose to rewrite it [either Python or C++ code] for more clarity?

**Comment by ExpHP** [comment]
Either `abs(delta)` or a comment that `-delta is nonnegative` on the same or previous line.

Ironically, in the python code it actually looks pretty clear, because there's fewer knobs to turn in the syntax.  (the `-delta` is clearly deliberate in that case, whereas in the C++ I have to take a moment and ask myself "why is the end value negated, but the condition is still `<=` and the increment is still `++`?")
